### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by gingerbeardman** [ixt/dotfiles#1]
Odd way to get in touch but I wanted to take you up on the offer to check our your PocketCHIP. 

http://www.lexaloffle.com/bbs/?tid=3274

Thanks!

**Comment by ixt** [comment]
Still waiting on it to ship, i will post again here when it arrives

**Comment by gingerbeardman** [comment]
cheers! :)

**Comment by ixt** [comment]
I have a pocketCHIP now, not currently in london but should be for a week from around the 20th. I am currently in reading, so if you happen to be around there. If else, you can ask me anything and I can try it out/try my best to answer

**Comment by gingerbeardman** [comment]
hey, thanks! I just moved to Cornwall so it's unlikely we'll be able to meet up. I really only wanted to know how workable the "d-pad" is but I hear that it's not good for diagonals. Cheers!

**Comment by ixt** [comment]
lovely place! the dpad sucks, I imagine it would be better with the overlaid 3d-print they promoted on the blog. but as it stands it is pretty much a press one direction at a time type deal, so diagonals are hard.
